[package]
name = "music_analyzer_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
midi_note_recorder = {git = "https://github.com/gjf2a/midi_note_recorder"}
enum-iterator = "2.3.0"
midi-msg = "0.8.1"
rand = "0.9.2"

[dev-dependencies]
anyhow = "1.0.100"
midi_fundsp = "0.7.0"
crossbeam-queue = "0.3.12"