[package]
name = "music_analyzer_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
midi_note_recorder = {git = "https://github.com/gjf2a/midi_note_recorder"}
enum-iterator = "2.3.0"
midi-msg = "0.8.1"
rand = "0.10.0"
midi_fundsp = "0.7.1"
bare_metal_modulo = "1.2.6"
hash_histogram = "0.13.0"
anyhow = "1.0.101"

[dev-dependencies]
anyhow = "1.0.100"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8"
