[package]
name = "music_analyzer_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
midi_note_recorder = {git = "https://github.com/gjf2a/midi_note_recorder"}
enum-iterator = "2.1"
midi-msg = "0.7"
rand = "0.8"

[dev-dependencies]
anyhow = "1"
